collector:
  interval: 1

lhm:
  enabled: "true"
  bridge_exe: 'lhm\sensor_bridge.exe'
  lhm_exe: 'lhm\LibreHardwareMonitor.exe'

update:
  enabled: "true"
  repo: "ai-written/monitorScreen"

background:
  image: ""
  opacity: 0.5
