// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DragEnd() {
  return window['go']['main']['App']['DragEnd']();
}

export function DragMove(arg1, arg2) {
  return window['go']['main']['App']['DragMove'](arg1, arg2);
}

export function DragStart(arg1, arg2) {
  return window['go']['main']['App']['DragStart'](arg1, arg2);
}

export function GetBackgroundImage() {
  return window['go']['main']['App']['GetBackgroundImage']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetIsFullscreen() {
  return window['go']['main']['App']['GetIsFullscreen']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
