// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DragEnd() {
  return window['go']['main']['App']['DragEnd']();
}

export function DragMove(arg1, arg2) {
  return window['go']['main']['App']['DragMove'](arg1, arg2);
}

export function DragStart(arg1, arg2) {
  return window['go']['main']['App']['DragStart'](arg1, arg2);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetIsFullscreen() {
  return window['go']['main']['App']['GetIsFullscreen']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
