// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DragEnd():Promise<void>;

export function DragMove(arg1:number,arg2:number):Promise<void>;

export function DragStart(arg1:number,arg2:number):Promise<void>;

export function GetDashboard():Promise<model.DashboardData>;

export function GetIsFullscreen():Promise<boolean>;

export function QuitApp():Promise<void>;

export function ShowWindow():Promise<void>;

export function Shutdown():Promise<void>;

export function ToggleFullscreen():Promise<void>;
